### ISSUE TITLE
[TODO] Account 作成

### ISSUE THREAD

**Issue by habvi** [42-pong/42-pong#110]
milestone だとチェックリストが使えなかったので TODO 用の Isseu を作成…

`Account` app
- #106
  - [x] まず認証なしでアカウント作成
- #123
  - [x] serializer の unit test 作成
- #143 
  - [x] docstring 追加
  - [x] `api/accounts/`, POST の integration test 作成
- #145 
  - [x] ユーザーを一意に識別する ID は、`user_id` で統一する (`player_id` は使わない)
- #161 
  - [x]  `oauth2` からでもアカウントを作れるように起点となる関数を作成 (`UserSerializer` を引数に渡して `PlayerSerializer` を作り、`User` と紐づく `Player` を作成する関数)
  - [x] error 時の response を `{"error": dict}` にした
- #178 
  - [x]  BE がランダム文字列の username を生成してアカウントのユーザー ID (UserModel の username) に使うため、ユニークか check してランダム文字列を返す関数作成
- #183
  - [x] # 178 のユニークランダムusenameを、account app 内の username に適用
  - [x] view の Response の JSON format をもう少しちゃんとする
- #191 
  - [x] `create_account()` の引数 `user_serializer` の `Meta.model` が `User` であることを確認する
- #192 
  - [x] email の重複登録をエラーにする
- #205 
  - [x] `create_account()` が `serializer.data` を返すように
- #210 
  - [x] `user`, `player`, `create_account` のディレクトリを作成して振分け
  - [x] `Player` model のユニットテスト追加
- #218 
  - [x] `create_acount()` にトランザクション処理追加
- #xxx
  - [ ] `create_account()` のテスト追加・修正
- #330 
  - [x] email の形式/文字数 などの validation (django の validation 調べる) -> EmailField 内の EmailValidator
  - [x] テスト追加
- #336 
  - [x] password の最小/最大長/hash化など？の validation (create_super_user() の validation 調べる)
  - [x] テスト追加

---
`Player`
- #221 
  - [x] `display_name`
    - [x] `display_name` を model に追加
    - [x] デフォルトを設定
    - [x] バリデーション追加
- #288 
  - [x] avatar を model に追加
  - [x] 各レスポンスに含めるように
- #289 
  - [x] avatar のデフォルト画像を設定
